name: Dev CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # 1. Java 21 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 1-2. application.yml 파일 생성
      - name: make application.yml
        run: |
          # create application.yml
          cd ./src/main
          cd ./resources

          # application.yml 파일 생성하기
          touch ./application.yml

          # Secrets에 저장한 값을 application.yml 파일에 쓰기
          echo "${{ secrets.DEV_YML }}" >> ./application.yml
        shell: bash # 스크립트가 Bash 셸에서 실행

      # 1-1. firebase serviceAccountKey.json 파일 생성
      - name: make firebase serviceAccountKey.json
        run: |
          mkdir -p ./src/main/resources/firebase
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > ./src/main/resources/firebase/serviceAccountKey.json

      # 2. Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew 
          ./gradlew clean build -x test

      # 3. Docker 이미지 빌드
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest .

      # 4. DockerHub 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Docker Hub 이미지 푸시
      - name: docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest

      # 6. 서버에서 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /
            sudo docker compose -f docker/docker-compose-dev.yml down
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest
            sudo docker compose -f /home/ubuntu/docker/docker-compose-dev.yml up -d
            sudo docker image prune -f